### ISSUE TITLE
Question newbie

### ISSUE THREAD

**Issue by thumble** [camisatx/pySecMaster#17]
Hi great work on pySecMaster, I am trying to become familiar with the process.
Is there a source for fundamental data (US and Canadian stocks)? Sorry it was not clear to me.

**Comment by camisatx** [comment]
Hi thumble, thanks for the kind words!

For US companies, there are a few sources for fundamental data (company financials).

The 2 free sources I know of are the [SEC EDGAR](https://www.sec.gov/edgar/searchedgar/companysearch.html) database and [Sharadar's](https://www.quandl.com/data/SF0-Free-US-Fundamentals-Data/documentation/about) free database on Quandl. EDGAR has all recent filings in XML files. I haven't built a scraper for the data yet (was on the todo list...), but it should be straightforward to build one. The hard part is matching different accounting terms companies use that actually represent the same (or similar) thing. Sharadar should take care of this for you. 

Sharadar recently made this data freely available, so if I were you, I'd start here. It's easy to work with Quandl's API.

There are other sources that charge a fee for this data, including [Sharadar's full US fundamental database](https://www.quandl.com/data/SF1-Core-US-Fundamentals-Data/documentation/about), [Zacks Fundamentals](https://www.quandl.com/data/ZFA-Zacks-Fundamentals-A-70-Indicators/documentation/introduction) and [xignite](http://www.xignite.com/) (if you need to burn a hole in your pocket!).

Since I've never used fundamental data with this system, I'm not sure if the fundamental table currently in the database would work. I expect it'd need to be modified, but that should be easy as no process uses that table.

Let me know if you need any clarification on this or other parts of the system.
